### ISSUE TITLE
Mondrian new version available.

### ISSUE THREAD

**Issue by dmitry-sloutskov** [rpbouman/xmondrian#6]
Hi Roland,
http://community.pentaho.com/projects/mondrian/

Direct download link http://sourceforge.net/projects/mondrian/files/mondrian/mondrian-3.13.0/mondrian-3.13.0.0-25.jar/download
Please, update your solution.

**Comment by rpbouman** [comment]
Thank you for your report. 

xmondrian.war has been updated to include 3.13 of mondrian.
additionally a new version of xavier was included.
