### ISSUE TITLE
How do i connect with MySQL database?

### ISSUE THREAD

**Issue by prabugithub** [rpbouman/xmondrian#7]

**Comment by prabugithub** [comment]
I am trying to connect MySQL database using XMondrian, I follow this [http://business-intelligence.phi-integration.com/2008/04/mondrian-mysql-setup.html] link for configuration. But i am getting below exception while choosing Xmlash.

Error: SOAP-ENV:Server.00HSBE02: XMLA Discover unparse results error
Error: The Mondrian XML: Mondrian Error:Internal error: No suitable connection found (00HSBE02)

I don't know what i am missing, it works for mondrian.war (3.5.0 version). How can i connect same here.

**Comment by rpbouman** [comment]
This is just a matter of the driver missing. Make sure the mysql jdbc driver jar is in the lib path of your servlet container.
This issue is not directly related to xmondrian.
